# Generated by Django 4.2 on 2023-04-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("support_group", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "system",
            },
        ),
        migrations.CreateModel(
            name="SystemContract",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("active", models.BooleanField(default=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=19)),
                ("amount_period", models.CharField(max_length=5)),
                ("amount_type", models.CharField(max_length=5)),
                (
                    "authorization_percent",
                    models.DecimalField(decimal_places=2, max_digits=19),
                ),
                ("from_date", models.DateField()),
                ("order_number", models.CharField(max_length=12)),
                ("request", models.CharField(max_length=12)),
                ("to_date", models.DateField()),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bluetask.system",
                    ),
                ),
            ],
            options={
                "db_table": "system_contract",
                "unique_together": {("request", "system")},
            },
        ),
    ]
